### ISSUE TITLE
Issue with token file

### ISSUE THREAD

**Issue by joe248** [ChrisMandich/PyFlume#1]
Hi Chris.  Thanks for creating this integration.  I'm attempting to try it out with Home Assistant and getting this error:

```
2019-11-18 09:36:43 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform flume
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/pyflume/__init__.py", line 128, in read_token_file
    with open(TOKEN_FILE, 'r') as token_file:
FileNotFoundError: [Errno 2] No such file or directory: 'flume_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/homeassistant/components/flume/sensor.py", line 44, in setup_platform
    flume_devices = FlumeDeviceList(username, password, client_id, client_secret)
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/pyflume/__init__.py", line 152, in __init__
    client_secret
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/pyflume/__init__.py", line 50, in __init__
    self.read_token_file()
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/pyflume/__init__.py", line 134, in read_token_file
    self.fetch_token()
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/pyflume/__init__.py", line 77, in fetch_token
    self.write_token_file()
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/pyflume/__init__.py", line 122, in write_token_file
    with open(TOKEN_FILE, 'w') as token_file:
PermissionError: [Errno 13] Permission denied: 'flume_token'
```

I'm not sure if the issue is that it's trying to open the token file that doesn't exist yet, or because it doesn't have the right permissions to create the file.

**Comment by joe248** [comment]
After looking at the code it appears the error occurs when trying to create the token file.  I changed the TOKEN_FILE to "/tmp/flume_token" and that worked.  Not sure if that's the most appropriate place to be storing the file but whatever the default directory is didn't work for me.

**Comment by ChrisMandich** [comment]
Hi Joe, looks like you resolved the issue. The token file writes to the current directory of the python interpreter. I initially wrote this to support Home Assistant, not sure if you saw my pull request that is now available in the Dev branch of HA? https://github.com/home-assistant/home-assistant/pull/27235

**Comment by joe248** [comment]
I saw that your PR was merged.  I'll try it once the next version of Home Assistant is released and see if the issue goes away.

**Comment by ChrisMandich** [comment]
Addressed here: https://github.com/ChrisMandich/PyFlume/commit/331a741a4f546c5d4f078ab6bb7415093a2891bd
